### ISSUE TITLE
not all messages are sent

### ISSUE THREAD

**Issue by matts93** [deFiss/telegram_channel_duplicator#4]
version before the update:

I noticed that it doesn't always copy the messages, I did some tests by quickly copying 5 messages on the terminal it displays sending to..
but instead of 5 I have 4,
in addition, sometimes it is as if it goes into stanby and does not copy even 1 message regardless

version after the last update:

seems to work better but still loses some messages if written quickly one after the other, even if they are on the terminal

**Comment by deFiss** [comment]
strange, in the last update, the control of already sent messages is carried out by their id, in the telegram it always monotonously increases, therefore, it is unlikely that any message can be missed, before  was really used a not very reliable mechanism based on the time of sending messages, we are sure that the problem is present on the latest version ?

**Comment by matts93** [comment]
I tested it for a few days and everything seems to work fine..
I thank you
